# Title of the CI - This title is the one that will apper in CI Git Actions.
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

  build:
    runs-on: ubuntu-latest
    needs: test          # 👈 solo corre si "test" pasó

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build package
        run: |
          mkdir -p dist
          zip -r dist/cicd-lab-build.zip app/ requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-lab-build
          path: dist/cicd-lab-build.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-lab-build-${{ github.run_number }}
          path: dist/cicd-lab-build.zip
          overwrite: true

  docker:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/cicd-lab:${{ github.run_number }} .
          docker tag ghcr.io/${{ github.repository_owner }}/cicd-lab:${{ github.run_number }} ghcr.io/${{ github.repository_owner }}/cicd-lab:latest

      - name: Run container (smoke test)
        run: docker run --rm ghcr.io/${{ github.repository_owner }}/cicd-lab:${{ github.run_number }}
      
      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/cicd-lab:${{ github.run_number }}
          docker push ghcr.io/${{ github.repository_owner }}/cicd-lab:latest



